# Generated by Django 2.2.2 on 2019-07-05 06:39

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=10)),
                ('pregnancy', models.CharField(max_length=10)),
                ('prescription', models.FileField(blank=True, upload_to=form.models.prescription_path)),
                ('lab_file', models.FileField(blank=True, upload_to=form.models.lab_files_path)),
            ],
        ),
    ]
